' Copyright (c) 2026 Fraunhofer-Gesellschaft zur Förderung der angewandten Forschung e.V.
'
' This work is licensed under the Fraunhofer License (on the basis of the MIT license)
' that can be found in the LICENSE file.

@startuml
!include style.puml

' === System Boundary ===
rectangle "Web Interface" as system {
    component "**App**" as app

    component "**Embed Tab**" as embedTab
    component "**Extract Tab**" as extractTab
}

component "**Watermarker Library**" as lib

' Internal
app --> embedTab
app --> extractTab

' External
embedTab --> lib : uses
extractTab --> lib : uses

@enduml
