
name: "Watermarker: Generate API docs"

on:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Generate API documentation
        working-directory: watermarker
        if: ${{ github.ref == 'refs/heads/main' && github.event_name != 'pull_request' }}
        run: ./gradlew dokkaHtml

      - name: Deploy API documentation to Github Pages
        if: ${{ github.ref == 'refs/heads/main' && github.event_name != 'pull_request' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: watermarker/build/dokka/html
          target-folder: docs
          commit-message: "docs(watermarker): updated API docs from @ ${{ github.repository }}@${{ github.sha }} 🚀"
